AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 512
    Architectures:
      - x86_64
  Api:
    EndpointConfiguration: REGIONAL
    Auth:
      ApiKeyRequired: true
      UsagePlan:
        CreateUsagePlan: SHARED

Resources:
  MRIRuby:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        Exec:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /exec/mri
            Method: post
    Environment:
      Variables:
        ENGINE_ARGS: "--disable-did_you_mean --disable-gems"
    Metadata:
      DockerTag: mriruby27
      DockerContext: ./app
      Dockerfile: Dockerfile
      DockerBuildArgs:
        RUBY_VERSION: 3.1.0

  MRIRubyDev:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        Exec:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /exec/mri/dev
            Method: post
      Environment:
        Variables:
          ENGINE_ARGS: "--disable-did_you_mean --disable-gems"
    Metadata:
      DockerTag: mrirubydev
      DockerContext: ./app
      Dockerfile: Dockerfile
      DockerBuildArgs:
        RUBY_VERSION: 3.2.0-dev

  TruffleRuby:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        Exec:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /exec/truffleruby
            Method: post
      Environment:
        Variables:
          ENGINE_ARGS: "--native"
    Metadata:
      DockerTag: truffleruby
      DockerContext: ./app
      Dockerfile: Dockerfile
      DockerBuildArgs:
        RUBY_VERSION: truffleruby-21.3.0

  JRuby:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        Exec:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /exec/jruby
            Method: post
      Environment:
        Variables:
          ENGINE_ARGS: "--dev"
    Metadata:
      DockerTag: jruby
      DockerContext: ./app
      Dockerfile: Dockerfile
      DockerBuildArgs:
        RUBY_VERSION: jruby-9.3.2.0

  MRuby:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Environment:
        Variables:
          ENGINE_ARGS: ""
      Events:
        Exec:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /exec/mruby/27
            Method: post
    Metadata:
      DockerTag: mruby
      DockerContext: ./app
      Dockerfile: Dockerfile
      DockerBuildArgs:
        RUBY_VERSION: mruby-3.0.0

  ArtichokeRuby:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Environment:
        Variables:
          ENGINE_ARGS: ""
          RUBY_BIN_PATH: "/opt/ruby/bin/artichoke"
      Events:
        Exec:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /exec/artichokeruby
            Method: post
    Metadata:
      DockerTag: artichokeruby
      DockerContext: ./app
      Dockerfile: Dockerfile.artichoke
      DockerBuildArgs:
        RUBY_VERSION: artichoke-dev

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com"