Parameters:
  UserName:
    Description: SAM Application Deployment user
    Type: String

Resources:
  DeployUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-deploy-bucket'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudformation:*'
                Resource: !Sub 'arn:aws:cloudformation:us-east-1:${AWS::AccountId}:stack/rubyapi-repl*'
              - Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                  - 's3:GetObject'
                Resource: !Join
                          - '/'
                          - - !GetAtt DeployBucket.Arn
                            - '*'

  DeployBucket:
    Type: AWS::S3::Bucket

  DeployRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Principal:
              Service: 'cloudformation.amazonaws.com'

      Path: /
      Description: Deployment role for Ruby API REPL service
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/IAMFullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
      RoleName: !Sub '${AWS::StackName}'
