Parameters:
  UserName:
    Description: SAM Application Deployment user
    Type: String

Resources:
  RubyAPIReplDeployUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName

  RubyAPIREPLDeployRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Description: Deployment role for Ruby API REPL service
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/IAMFullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
      RoleName: !Sub '${AWS::StackName}'