name: AWS SAM

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies with Apt Get
        run: |
          sudo apt update && sudo apt install python3.8 jq -y
      - name: SAM Validate
        run: |
          sam validate
      - name: SAM Build
        run: |
          sam build