name: Docker

on:
  push:
    # branches:
    #   - main
    # paths-ignore:
    #   - '**.md'
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - '**.md'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.json }}
    steps:
    - uses: actions/checkout@v3

    - id: set-matrix
      run: |
        payload=$(cat versions.json)
        payload="${payload//'%'/'%25'}"
        payload="${payload//$'\n'/'%0A'}"
        payload="${payload//$'\r'/'%0D'}"
        echo "::set-output name=json::$payload"
  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.setup.outputs.matrix)}}
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: rubyapi/repl:${{matrix.engines.name}}
          build-args: RUBY_VERSION=${{matrix.engines.version}} JAVA_REQUIRED=${{matrix.engines.java}}